name: cp-vton
channels:
  - pytorch
  - defaults
dependencies:
  - matplotlib=3.0.0
  - numpy=1.15.2
  - pillow=5.2.0
  - pip=10.0.1
  - python=3.5.6
  - pytorch=0.4.1
  - torchvision=0.2.1
  - pip:
    - tensorboard==1.6.0
    - tensorboard-pytorch==0.7.1
    - tensorboardx==1.1
