#!/bin/bash

export GCRM_MACHINE_TYPE=GPU  # CPU GPU
export GCRM_ZONE=us-central1-a  # europe-west2-c us-central1-b europe-west4-a

export GCRM_SPECIAL_MACHINE_IMAGE_FAMILY=pytorch-0-4-cu91  # can be left empty
